language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lucasrohlf/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run lucasrohlf/react-test npm test -- --coverage

after_success:
    - docker build -t lucasrohlf/multi-client ./client
    - docker build -t lucasrohlf/multi-nginx ./nginx
    - docker build -t lucasrohlf/multi-server ./server
    - docker build -t lucasrohlf/multi-worker ./worker

# Log into docker CLI via one command using Env Vars of travis CI project
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push them up to docker-hub
    - docker push lucasrohlf/multi-client
    - docker push lucasrohlf/multi-nginx
    - docker push lucasrohlf/multi-server
    - docker push lucasrohlf/multi-worker

# Tell AWS to download and run the images
deploy: 
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-825842704967
    bucket_path: docker-multi
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master